spring:
  application:
    name: rabbitmq-stream
  rabbitmq:
    host:
    port: 5672
    username: guest
    password: guest
    virtual-host: /

server:
  port: 8080
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024
  http2:
    enabled: true


